name: hands_on_platform_version_example
description: Demonstrates how to use the hands_on_platform_version plugin.
version: 0.0.1
author: Alessandro Biessek <alessandrobiessek@gmail.com>
# homepage: the plugin homepage

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  hands_on_platform_version:
    path: ../

flutter:
  uses-material-design: true
