name: simple_package_structure
description: A simple package example
homepage: https://www.example.com
author: Alessandro Biessek <alessandrobiessek@gmail.com>

environment:
  sdk: '>=2.0.0 <3.0.0' # check the dependencies section below to understand deps versioning

dependencies:
  json_serializable: ^2.0.1

dev_dependencies:
  test: ^1.0.0
